---
title: "Homework 1 Part 1"
author: "Henry Surjono"
date: "2024-01-27"
output: pdf_document
---
```{r}
library(rgl)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Problem 1: Graphing a bivariate function and its second order approximation

i) Write an R function that computes the function $f$ for any input $x_1$ and $x_2$
```{r}
f <- function(x1,x2) {cos(x1*x2)}
```

ii) Write an R function that computes the function $h$ for any input $x_1$, and $x_2$

```{r}
h <- function(x1,x2) {1 - ((pi^2/8)*(x1)^2)}
```

iii) and iv)

```{r}
x1 <- seq(from = -pi/4, to = pi/4, length = 30)
x2 <- seq(from = pi/4, to = 3*pi/4, length = 30)
f1 <- outer(x1, x2, FUN = f)
persp3d(x1, x2, f1, col = "red", shade = 0.1 ,alpha = 0.5, xlab = "x1", ylab = "x2", main = "Taylor approximation of cos(x1x2)")
h1 <- outer(x1, x2, FUN = h)
persp3d(x1,x2, h1, col = "blue", shade = 0.1, alpha = 0.5, add = TRUE)
rglwidget(controllers = ) 
```

v and vi
```{r}
errorf <- abs(f1 - h1)
persp3d(x1, x2, errorf, col = "red", alpha = 0.5, xlab = "x1", ylab = "x2", main = "The error in second order Taylor expansion of cos(x1x2)")
rglwidget(controllers = ) 
```
vii
```{r}
filled.contour(x1, x2, errorf)
grid(nx = 20, ny = 20)
```


