---
title: "HW6.2"
author: "Michael Pena"
date: "2024-04-20"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(mvtnorm)
```

# problem 1

# part (a)

```{r}
# general importance sampling
ISE <- function(f,g,h,n){
 return(list(Theta = mean(h*f/g), StandErr = sqrt(var(h*f/g)/n)))
}

# generate values from cauchy
N <-20000
y <- rcauchy(N)
# render function vectors
fy <- rep(0,N)
# making sure f(y) only passes values between 0 and 1
for(i in 1:N){
  if(y[i] >= 0 & y[i] <= 1){fy[i] =  exp(-y[i])/(1-exp(-1))}
}
gy <- 1/(pi*(1+y^2))
hy <- 1/(1 + y^2)

#get estimations
ISE(fy,gy,hy,N)
```

# part (b).

```{r}
# generate trucated cauchy samples
y <- rep(0,N)
for(i in 1:N){
  repeat{
    Z <- rcauchy(1)
    if(Z <= 1 & Z >= 0){
      Z -> y[i]
      break
    }
  }
}
# render function vectors
fy <- rep(0,N)
# making sure f(y) only passes values between 0 and 1
for(i in 1:N){
  if(y[i] <= 1){fy[i] =  exp(-y[i])/(1-exp(-1))}
}
hy <- 1/(1 + y^2)
gy <- 4/(pi*(1+y^2))
# get estimations
ISE(fy,gy,hy,N)
```

# part (c).

```{r}
# generate exp samples
rexp(N) -> y
# render function vectors
fy <- rep(0,N)
# making sure f(y) only passes values below 1 (rexp doesn't gen negatives)
for(i in 1:N){
  if(y[i] <= 1){fy[i] =  exp(-y[i])/(1-exp(-1))}
}
hy <- 1/(1 + y^2)
gy <- exp(-y)
# get estimations
ISE(fy,gy,hy,N)
```


# problem 2

```{r}
# render X_i from the trivariate - t
cov <-  matrix(c(1,3/5,1/3,3/5,1,11/15,1/3,11/15,1),3,3,byrow = T)
muv <- c(0,0,0)
X <- as.matrix(rmvnorm(N,mean = muv, sigma = cov))

# render pmfs
gX <- dmvnorm(X,mean = muv,sigma = cov)
fX = rep(0,N)
  for (i in 1:N) {
    fX[i] <- (5 + (t(X[i,])) %*% solve(cov)%*%(X[i,]))^-4
  }
wX <- fX/gX
T0 = sum(wX)

#make indicator
I = as.numeric(X[,1] <= 1 & X[,2] <= 4 & X[,3] <= 2 )

# render 
theta = sum(I*wX)/T0
theta
```


# problem 3

# part (a)


set pdfs equal to eachother 
case I: $y < 0$

$$
\frac{e^{y}}{2} = \frac{e^{-y^2/2}}{\sqrt{2\pi}}\\
e^y = \frac{2e^{-y^2/2}}{\sqrt{2\pi}}\\
e^y\cdot e^{y^2/2} = \frac{2}{\sqrt{2\pi}}\\
e^{y+\frac{y^2}{2}} = \sqrt{\frac{2}{\pi}}\\
y + \frac{y^2}{2} = ln[\sqrt{\frac{2}{\pi}}]\\
\frac{1}{2}y^2+y-\frac{1}{2}ln[2/\pi]=0
$$

```{r}
a = .5
b = 1
c = -0.5*log(2/pi)
y1 = (-b-sqrt(b^2 - 4*a*c))/2*a
y2 = (-b+sqrt(b^2 - 4*a*c))/2*a
y1;y2
```

likewise 
 case II: $y >0 $

$$
\frac{1}{2}y^2-y-\frac{1}{2}ln[2/\pi]=0
$$

```{r}
a = .5
b = -1
c = -0.5*log(2/pi)
y1 = (-b-sqrt(b^2 - 4*a*c))/2*a
y2 = (-b+sqrt(b^2 - 4*a*c))/2*a
y1;y2
```

# part (b).

$\alpha$ will be the maximum of $g(y)/f_Y(y)$, thus

$$
0 = \frac{d}{dy}\bigg(
\frac{1}{2}e^{-|y|}\cdot \sqrt{2\pi} \cdot e^{y^2/2} 
\bigg)\\
0 = \sqrt{\frac\pi{2}}\frac{d}{dy}\bigg(
e^{-|y|+y^2/2} 
\bigg)\\
$$
when $y > 0 $

$$
0 = \sqrt{\frac\pi{2}}
e^{-y+y^2/2}(-y+1) \\
y^* = 1
$$
likewise when $y < 0$

$$
0 = \sqrt{\frac\pi{2}}
e^{y+y^2/2}(y+1) \\
y^* = -1
$$

notice $g(1)/f_Y(1) = g(-1)/f_Y(-1) = 0.7601735$

# part (c).

```{r}
# render math functions 
f <- function(x){
 exp(-(x^2)/2)/sqrt(2*pi)
}

g <- function(x){
 exp(-1*abs(x))/2
}

N = 10000
alpha = g(1)/f(1)
# open norm vector
norm_x <- rep(0,N)

for(i in 1:N){
 repeat{
  y <- -log(runif(1)) # inverse of double exponential
  u <- runif(1)
  if(u < f(y)*alpha/g(y)){break}
 }
 
 if(runif(1) < .5){
  Z = y
 }else{Z = -y}
 
  Z -> norm_x[i]
}

hist(norm_x, prob = T, breaks = 50)
curve(dnorm(x),add=T,lwd = 3.5, col = "forestgreen")
```

