---
title: "MP536Final"
author: "Michael Pena"
date: "2024-05-14"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
library(rpart)
library(adabag)
library(randomForest)
library(ROCR)
library(gbm)
```


```{r}
# load in data
data <- read.csv("baseball.csv", head = T)

```

```{r}
# model the data
ggplot(data = data) +
  geom_point(aes(x = plate_x, y = plate_z, color = description))
```

```{r}
# filter data
data <- filter(data, !is.na(plate_x))
data <- filter(data, !is.na(plate_z))

n = length(data$pitch_type)
zone = data.frame()

a1 = 1.2
b1 = 1.2
a2 = .96
b2 = .96

  
for (i in 1:n){
  X <- data$plate_x[i]
  Y <- data$plate_z[i]
  if((X^2/a1^2 + (Y - 2.5)^2/b1^2 <= 1) & (X^2/a2^2 + (Y - 2.5)^2/b2^2 >= 1)){
    zone = rbind(zone,data[i,])
  }
}

# model the data
ggplot(data = zone) +
  geom_point(aes(x = plate_x, y = plate_z, color = description))
```

```{r}
# remove X
zone <- zone %>% select(-X)
zone$description = as.factor(zone$description)
```


```{r}
# call equation
equa1 = description ~ plate_x + plate_z + balls + strikes + release_speed + home_score + away_score
# form Rand Forest model
model.rf = randomForest(equa1,data=zone,ntree=7000,mtry=3,control=rpart.control(minsplit=5,cp=.02))
summary(model.rf)
print(model.rf)
```
>> GAMEPLAN
 >
 > + get prediction probabilities for when all ball = 0, all ball =1, etc...
 > + graph the probabilities using boxplot
 > + repeat for boosting

```{r}
plot(model.rf)
```

```{r}
# as factor for some data 
zone$description <-  as.factor(zone$description)
# adap boosting portion
model.ab = boosting(equa1,data=zone,mfinal=100,control=rpart.control(minsplit=10,cp=.02))

prediction.ab = model.ab$class
table(prediction.ab,zone$description)
```



```{r}
y = as.numeric(zone$description) - 1

p.b = predict(model.rf,newdata=zone,type="prob")[,2]
#Probably don't want rounded probabilities to exactly 0 or 1

p.b[p.b==0] = 0.00001
p.b[p.b==1] = .9999
LL.b = sum(y*log(p.b) + (1-y)*log(1-p.b))

LL.b


```

```{r}
FiveFold <- function(ntree.in, mfinal.in, cp.in, ms.in){
###model b wins by a mile, but I'm a little worried about overfitting.  Time to cross validate)
###Going to 10 fold cross validate
set.seed(536)
n = dim(zone)[1]

###with 179 data points, going to have 17 data points in each testing set
###Obviously that means there are 9 data points that never get partitioned
###as testing data.  But we can pick those up as their own testing group at the end if we want to.

CV.ind.mat = matrix(sample(1:n,3070,replace=F),nrow=5)

#Run same code as before, but each time, we're going to run our models using only train data
#and testing them using only testing data.
CVLL.a = 0
CVLL.b = 0
for(k in 1:5){
	train.data = zone[(1:n)[-CV.ind.mat[k,]],]
	
	test.data = zone[CV.ind.mat[k,],]

 model.a = randomForest(description ~ plate_x + plate_z + balls + strikes + release_speed + home_score + away_score,
                        data = train.data, ntree = ntree.in, mtry = 3, control=rpart.control(minsplit=ms.in,cp=cp.in))
 model.b = boosting(description ~ plate_x + plate_z + balls + strikes + release_speed + home_score + away_score,
                    data = train.data, mfinal=mfinal.in, control=rpart.control(minsplit=ms.in,cp=cp.in))

  	
	y = (as.numeric(zone$description) - 1)[CV.ind.mat[k,]]
	p.a = predict(model.a,newdata=test.data,type="prob")[,2]
	p.b = predict(model.b,newdata=test.data)$prob[,2]
	#Probably don't want rounded probabilities to exactly 0 or 1
	p.a[p.a==0] = 0.00001
	p.a[p.a==1] = .9999	
	
	p.b[p.b==0] = 0.00001
	p.b[p.b==1] = .9999

	LL.a1 = sum(y*log(p.a) + (1-y)*log(1-p.a))
	LL.b1 = sum(y*log(p.b) + (1-y)*log(1-p.b))
	CVLL.a = CVLL.a + LL.a1
	CVLL.b = CVLL.b + LL.b1
}
 ROW <- c(CVLL.a,CVLL.b,ntree.in, mfinal.in, cp.in, ms.in)
 return(ROW)
}
```


```{r}
start = date()
FiveFold(200,200,.01,8)
end = date()
```


```{r}
LLdf <- data.frame()
start = date()
for(i.tr in c(100,500,1000)){
  for(i.cp in c(.001,.01,.05)){
    for(i.ms in c(5,10,20)){
      row <- FiveFold(i.tr,i.tr,i.cp,i.ms)
      LLdf <- rbind(LLdf,row)
    }
  }
}
end = date()
```

```{r}
startF = date()
FiveFold(1000,1000,.05,5) -> x1
endF = date()
```

# simulating balls = i

```{r}
# render idealmodel here

idealmodel = NULL
```


```{r}
# sim data to plug into ideal model
zone0 <- zone %>% mutate(balls = 0)
zone1 <- zone %>% mutate(balls = 1)
zone2 <- zone %>% mutate(balls = 2)
zone3 <- zone %>% mutate(balls = 3)
```

```{r}
# if the idealmodel is RandForest
	 P0 = predict(idealmodel,newdata=zone0,type="prob")[,2]
	 P1 = predict(idealmodel,newdata=zone1,type="prob")[,2]
	 P2 = predict(idealmodel,newdata=zone2,type="prob")[,2]
	 P3 = predict(idealmodel,newdata=zone3,type="prob")[,2]
```


```{r}
# if the idealmodel is AB
   P0 = predict(idealmodel,newdata=zone0)$prob[,2]
	 P1 = predict(idealmodel,newdata=zone1)$prob[,2]
	 P2 = predict(idealmodel,newdata=zone2)$prob[,2]
	 P3 = predict(idealmodel,newdata=zone3)$prob[,2]
```


```{r}
# Plotting multiple boxplots on the same graph
boxplot(P0, P1, P2, P3, 
        names = c("Balls = 0", "Balls = 1", "Balls = 2", "Balls = 3"),
        col = c("skyblue", "lightgreen", "lightpink", "blanchedalmond"),
        main = "Multiple Boxplots",
        xlab = "Groups",
        ylab = "Probability")

```

